# Generated by Django 5.2.11 on 2026-02-06 03:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("analyzer", "Content Analyzer"),
                            ("generator", "Content Generator"),
                            ("reviewer", "Quality Reviewer"),
                            ("router", "Task Router"),
                            ("orchestrator", "Orchestrator"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("system_prompt", models.TextField()),
                (
                    "capabilities",
                    models.JSONField(default=list, help_text="List of capability tags"),
                ),
                (
                    "model_preference",
                    models.CharField(default="gpt-4o-mini", max_length=100),
                ),
                ("max_tokens", models.IntegerField(default=1024)),
                ("temperature", models.FloatField(default=0.7)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "mcp_endpoint",
                    models.CharField(
                        blank=True, help_text="MCP protocol endpoint", max_length=500
                    ),
                ),
                (
                    "a2a_card",
                    models.JSONField(
                        blank=True, default=dict, help_text="A2A Agent Card metadata"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "workflow_id",
                    models.UUIDField(help_text="Groups related agent executions"),
                ),
                ("input_data", models.TextField()),
                ("output_data", models.TextField(blank=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("tokens_used", models.IntegerField(default=0)),
                ("latency_ms", models.IntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="agents.agentdefinition",
                    ),
                ),
                (
                    "parent_execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agents.agentexecution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
